In [1]:
import numpy as np


In [2]:
#(1) create a 1D numpy array containaing the numbers frim 10 to 50 (inclusive) with a step of 5
arr = np.arange(10, 51, 5)
print(arr)


[10 15 20 25 30 35 40 45 50]


In [3]:
#(2) create a 4*6 array filled with zeros then fill it's third row (index 2) with the value 99
zeros = np.zeros((4, 6))
print(zeros)
zeros[2, :] = 99
print(zeros)


[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [99. 99. 99. 99. 99. 99.]
 [ 0.  0.  0.  0.  0.  0.]]


In [4]:
#(3) given the following 1D array, print all elements that are greater than 50
arr = np.array([12, 45, 7, 19, 88, 3, 56, 91, 24, 67])
print(arr[arr > 50])

[88 56 91 67]


In [5]:
#(4) create a 5*5 identity matrix, then change it's main diagonal to the values of
# 10, 20, 30, 40, 50
mat = np.eye(5)
print(mat)
mat = np.diag([10, 20, 30, 40, 50])
print(mat)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[10  0  0  0  0]
 [ 0 20  0  0  0]
 [ 0  0 30  0  0]
 [ 0  0  0 40  0]
 [ 0  0  0  0 50]]


In [6]:
#(5) let 
x = np.arange(1, 21).reshape(4, 5)
# extract the following using slicing:
# 1. the last two rows
print(x[2:, :])
# 2. the third column
print(x[:, 2])
# 3. the 3x3 matrix in the top-right corner
print(x[:3, 2:5])


[[11 12 13 14 15]
 [16 17 18 19 20]]
[ 3  8 13 18]
[[ 3  4  5]
 [ 8  9 10]
 [13 14 15]]


In [8]:
#(6) given two arrays:
a = np.array([1, 2, 3, 4])
b = np.array([[10], [20], [30]])
# compute a + b and explain the result
result = a + b
print(result)
"""numpy broadcasts 
the shapes of the arrays to make them compatible with the operation. array (a) has shape (4,) and array b has
shape (3, 1). then numpy broadcasts array (a) to be like the shape of array b, the result is (3, 4)"""


[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


'numpy broadcasts \nthe shapes of the arrays to make them compatible with the operation. array (a) has shape (4,) and array b has\nshape (3, 1). then numpy broadcasts array (a) to be like the shape of array b, the result is (3, 4)'

In [10]:
#(7) normalize the following array to the range [0, 1]
arr = np.array([150, 220, 90, 300, 180, 45])
normalized = (arr - arr.min()) / (arr.max() - arr.min())
print(normalized)


[0.41176471 0.68627451 0.17647059 1.         0.52941176 0.        ]


In [11]:
#(8) standardize the same array from question 7
standardized = (arr - arr.mean()) / arr.std()
print(standardized)


[-0.16988961  0.66956492 -0.88942206  1.62894153  0.18987662 -1.42907141]


In [12]:
#(9) given the following 2d array:
mat = np.array([[ 4,  8,  1,  12],
                [7,  3,  9,  5],
                [11,  2, 6,  10],
                [15, 0, 14, 13]])
# a compute the mean of each row
row_means = mat.mean(axis=1)
print(row_means)
# b compute the sum of each column
col_sums = mat.sum(axis=0)
print(col_sums)
#c find the maximum value in the entire matrix and its position (row and column)
max_value = mat.max()
max_position = np.unravel_index(mat.argmax(), mat.shape)
print(max_value)
print(max_position)

[ 6.25  6.    7.25 10.5 ]
[37 13 30 40]
15
(3, 0)


In [16]:
#10 reshape the array np.arange(36) into a 3d array with shape (3, 4, 3)
reshaped = np.arange(36).reshape(3, 4, 3)
print(reshaped)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]]


In [17]:
#11 given arr = np.arange(1, 17).reshape(4, 4) reverse the order of the rows and columns
arr = np.arange(1, 17).reshape(4, 4)
reversed_arr = arr[::-1, ::-1]
print(reversed_arr)

[[16 15 14 13]
 [12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [18]:
#(12)
ages = np.array([23, 45, 19, 34, 28, 51, 17, 39])
names = np.array(['Ali', 'Sara', 'Omar', 'Lina', 'Khaled', 'Nour', 'Yara', 'Hassan'])
#get the names of people whos age is between 25 amd 40 (inclusive)
filtered_names = names[( ages >= 25) & (ages <= 40)]
print(filtered_names)

['Lina' 'Khaled' 'Hassan']


In [19]:
#(13) using the same ages and names arrays, replace all ages less than 20 with 20
ages[ages < 20] = 20
print(ages)

[23 45 20 34 28 51 20 39]


In [20]:
#(14) create a 6x6 array filled with random integers between 0 and 100 (inclusive) then set seed to 123 first
np.random.seed(123)
random_array = np.random.randint(0, 101, size=(6, 6))
print(random_array)

[[66 92 98 17 83 57]
 [86 97 96 47 73 32]
 [46 96 25 83 78 36]
 [96 80 68 49 55 67]
 [ 2 84 39 66 84 47]
 [61 48  7 99 92 52]]


In [21]:
#(15) create an array of 10 random numbers from normal distribution with mean 10 and standard deviation 15
normal_array = np.random.normal(loc=10, scale=15, size=10)
print(normal_array)

[ 37.06686834  -4.48325039  -9.74720052   0.61322265   5.09580659
   5.37686206  22.40676196  26.06172126 -35.83366126  25.08897902]


In [22]:
#(16) from the list colors = ['red', 'blue', 'green', 'yellow', 'purple'], randomly select 3 colors without replacement
colors = ['red', 'blue', 'green', 'yellow', 'purple']
selected_colors = np.random.choice(colors, size=3, replace=False)
print(selected_colors)

['blue' 'yellow' 'purple']


In [23]:
#(17) shuffle the numbers from 1 to 20 in place
numbers = np.arange(1, 21)
np.random.shuffle(numbers)
print(numbers)


[14  4  1  7 13 15 16 17  9  5  3 10 18  6 11 19  2 20 12  8]
